#include "GameSavePluginPrivatePCH.h"
#include "SaveSlotType.h"

EVENT_TYPE_STR_DEFINE(OBJECT, "Object");
EVENT_TYPE_STR_DEFINE(ACTOR, "Actor");
EVENT_TYPE_STR_DEFINE(CHARACTER, "Character");
EVENT_TYPE_STR_DEFINE(LEVEL, "Level");
EVENT_TYPE_STR_DEFINE(GAMEINSTANCE, "GameInstance");
EVENT_TYPE_STR_DEFINE(GAMEMODE, "GameMode");
EVENT_TYPE_STR_DEFINE(GAMESTATE, "GameState");